config/routes.rb
Rails.application.routes.draw do
  resources :users
  resources :beers
  resources :breweries
  resource :session, only: [:new, :create, :delete]
root 'breweries#index'
get 'kaikki_bisset', to: 'beers#index'
get 'signup', to: 'users#new'
get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'

resources :ratings, only: [:index, :new, :create, :destroy]

end

app/models/rating.rb
class Rating < ActiveRecord::Base
  belongs_to :beer
  belongs_to :user

 validates :score, numericality: { greater_than_or_equal_to: 1,
                                    less_than_or_equal_to: 50,
                                    only_integer: true }

def to_s
  "#{beer.name} #{score}"

end
end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  

  # GET /ratings
  # GET /ratings.json
  def index
    @ratings = Rating.all
  end
  def new
    @rating = Rating.new
    @beers = Beer.all
  end

#    def create
#    rating = Rating.create params.require(:rating).permit(:score, :beer_id)
#    current_user.ratings << rating
#    redirect_to current_user
#  end

  def create
    @rating = Rating.new params.require(:rating).permit(:score, :beer_id)

    if @rating.save
      current_user.ratings << @rating
      redirect_to user_path current_user
    else
      @beers = Beer.all
      render :new
    end
  end
  def destroy
    rating = Rating.find params[:id]
    rating.delete if current_user == rating.user
    redirect_to :back
  end
end

app/views/ratings/_form.html.erb
<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited this rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :score %><br>
    <%= f.text_field :score %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/ratings/edit.html.erb
<h1>Editing Rating</h1>

<%= render 'form' %>

<%= link_to 'Show', @rating %> |
<%= link_to 'Back', ratings_path %>

app/views/ratings/index.html.erb
<h2>List of ratings</h2>

<ul>
<% @ratings.each do |rating| %>
    <li> <%= rating %> <%= link_to rating.user.username, rating.user %> </li>
  <% end %>
</ul>


<%= link_to 'New Rating', new_rating_path %>

app/views/ratings/new.html.erb
<h2>Create new rating</h2>

<%= form_for(@rating) do |f| %>
  <% if @rating.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rating.errors.count, "error") %> prohibited rating from being saved:</h2>

      <ul>
      <% @rating.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.select :beer_id, options_from_collection_for_select(@beers, :id, :to_s) %>
  score: <%= f.number_field :score %>
  <%= f.submit %>

<% end %>

app/views/ratings/show.html.erb
<p id="notice"><%= notice %></p>

<h2><%= @rating.score %></h2>


<%= link_to 'list of beers', beers_path %> |
<%= link_to 'Edit', edit_brewery_path(@brewery) %> |
<%= link_to 'Back', breweries_path %>